### PR TITLE
Authentication Page and Route Protection

### LINKED ISSUE #2: LogIn/SignUp Page
We need to create an authentication page for users to access the control panel. Current structure is using http-only cookies so we do not need to do much than get the data and send it to the API.

Whenever a secured/private route is tried to be reached and API returned and unauthorised exception, we need to redirect the user to the authentication page.

### PR DESCRIPTION
**Pull request by ErtyumPX**
Closes #2 

## What are we doing with this PR?

This PR is:
- Creating a panel route, adding `/panel` and `/panel/auth` pages, `/panel` is the general console for the user that needs to be protected, `/panel/auth` is the login page
- Creating a `middleware.ts` file that is currently matching every route in `/panel` except auth page. If the user is not authenticated, it redirects the user to the auth page.
- Using `Tremor` features to create a simple login/signup layout, have a form that checks a simple regex and submit the form.

## Notes

You may check [here](https://nextjs.org/docs/app/building-your-application/routing/middleware) to see how `middleware.ts` works with NextJS.

You can also check [tremor components and docs](https://www.tremor.so/components).

### CODE REVIEW

File: src/middleware.ts [hunk 1]
```diff
@@ -0,0 +1,32 @@
...
+  const redirectUrl = new URL(authPage, req.url);
+  return NextResponse.redirect(redirectUrl);
+}
+
+const validateToken = async (allCookies: any) => {
+  const response = await fetch(`${APIService.baseURL}/auth/validate`, {
+    method: "POST",
+    headers: {
+      "Content-Type": "application/json",
+    },
```
Comment (Utkub24) [inline src/middleware.ts:28]: This is a very common pattern used in requests. Maybe we could have a central service for generating these?

File: src/app/panel/auth/SignUp.tsx [hunk 2]
```diff
@@ -0,0 +1,90 @@
...
+  };
+
+  const onUsernameChange = (e: React.ChangeEvent<HTMLInputElement>) => {
+    e.target.value = e.target.value.replace(/[^a-zA-Z0-9]/g, '');
+    setUsername(e.target.value);
+    validateForm();
+  }
+
+  const onEmailChange = (e: React.ChangeEvent<HTMLInputElement>) => {
+    e.target.value = e.target.value.replace(/[^a-zA-Z0-9]/g, '');
```
Comment (Utkub24) [inline src/app/panel/auth/SignUp.tsx:25]: This is missing an '@' and a '.' Rather crucial in an email I think.

```suggestion
  const onEmailChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    e.target.value = e.target.value.replace(/[^a-zA-Z0-9@.]/g, '');
```

File: src/app/panel/auth/SignUp.tsx [hunk 3]
```diff
@@ -0,0 +1,90 @@
...
+      setIsFormValid(false);
+    }
+    else if (email.length < 3) {
+      setIsFormValid(false);
+    }
+    else if (password !== confirmPassword) {
+      setIsFormValid(false);
+    }
+    else if (password.length < 8) {
+      setIsFormValid(false);
```
Comment (Utkub24) [inline src/app/panel/auth/SignUp.tsx:53]: Why not OR all of these conditions together? :pray:

**Review by Utkub24 — APPROVED** [review]
Cool +1

File: src/app/panel/auth/SignUp.tsx (hunk 2 above)
Comment (ErtyumPX) [reply src/app/panel/auth/SignUp.tsx:25]: I totally forgot to go back to this part, let me check again <3

File: src/app/panel/auth/SignUp.tsx (hunk 3 above)
Comment (ErtyumPX) [reply src/app/panel/auth/SignUp.tsx:53]: I choose to go this way in `SignUp` component in case we wanted to give different warnings to the user, which are also not added yet ^^

File: src/app/panel/auth/LogIn.tsx [hunk 4]
```diff
@@ -0,0 +1,70 @@
...
+
+  const validateForm = (): void => {
+    if (username.length < 1) {
+      setIsFormValid(false);
+    }
+    else if (password.length < 1) {
+      setIsFormValid(false);
+    }
+    setIsFormValid(true);
+  }
```
Comment (HuseyinSimsek7904) [inline src/app/panel/auth/LogIn.tsx:36]: I believe, it would make sense if the front-end application also limited the maximum number of characters in usernames and passwords.

File: src/app/panel/auth/LogIn.tsx [hunk 5]
```diff
@@ -0,0 +1,70 @@
...
+
+  const onUsernameChange = (e: React.ChangeEvent<HTMLInputElement>) => {
+    e.target.value = e.target.value.replace(/[^a-zA-Z0-9]/g, '');
```
Comment (HuseyinSimsek7904) [inline src/app/panel/auth/LogIn.tsx:39]: Do we really want to replace these characters? I think we should instead change the validateForm function to check for invalid characters as well.

File: src/app/panel/auth/LogIn.tsx [hunk 6]
```diff
@@ -0,0 +1,70 @@
...
+    setUsername(e.target.value);
+    validateForm();
+  }
+
+  const onPasswordChange = (e: React.ChangeEvent<HTMLInputElement>) => {
+    e.target.value = e.target.value.replace(/[^a-zA-Z0-9]/g, '');
```
Comment (HuseyinSimsek7904) [inline src/app/panel/auth/LogIn.tsx:45]: Same here.

File: src/app/panel/auth/SignUp.tsx [hunk 7]
```diff
@@ -0,0 +1,90 @@
...
+    validateForm();
+  }
+
+  const onConfirmPasswordChange = (e: React.ChangeEvent<HTMLInputElement>) => {
+    e.target.value = e.target.value.replace(/[^a-zA-Z0-9]/g, '');
+    setConfirmPassword(e.target.value);
+    validateForm();
+  }
+
+  const validateForm = (): void => {
```
Comment (HuseyinSimsek7904) [inline src/app/panel/auth/SignUp.tsx:42]: Why are we redefining this function? I think there can be a common service that does this which both SignIn and SignUp could use.

File: src/app/panel/auth/SignUp.tsx [hunk 8]
```diff
@@ -0,0 +1,90 @@
...
+  }
+
+  const onEmailChange = (e: React.ChangeEvent<HTMLInputElement>) => {
+    e.target.value = e.target.value.replace(/[^a-zA-Z0-9]/g, '');
+    setEmail(e.target.value);
+    validateForm();
+  } 
+
+  const onPasswordChange = (e: React.ChangeEvent<HTMLInputElement>) => {
+    e.target.value = e.target.value.replace(/[^a-zA-Z0-9]/g, '');
```
Comment (HuseyinSimsek7904) [inline src/app/panel/auth/SignUp.tsx:31]: Just like the comment in SignIn.

File: src/app/panel/auth/SignUp.tsx [hunk 9]
```diff
@@ -0,0 +1,90 @@
...
+    setPassword(e.target.value);
+    validateForm();
+  }
+
+  const onConfirmPasswordChange = (e: React.ChangeEvent<HTMLInputElement>) => {
+    e.target.value = e.target.value.replace(/[^a-zA-Z0-9]/g, '');
```
Comment (HuseyinSimsek7904) [inline src/app/panel/auth/SignUp.tsx:37]: Same here.

File: src/app/panel/page.tsx [hunk 10]
```diff
@@ -0,0 +1,10 @@
+"use client";
+
+export default function Home() {
+
+  return (
+    <main>
+      <h1>Controle Panel</h1>
```
Comment (HuseyinSimsek7904) [inline src/app/panel/page.tsx:7]: Is this intentional? `Controle` and not `Control`?

File: src/services/api.ts [hunk 11]
```diff
@@ -0,0 +1,47 @@
...
+      body: JSON.stringify({ 
+        "username": username, 
+        "password": password 
+      }),
+      headers: {
+        'Content-Type': 'application/json',
+      },
+      credentials: 'include',
+    });
+    console.log(response);
```
Comment (HuseyinSimsek7904) [inline src/services/api.ts:16]: Isn't this a debug statement? Should we really be pushing these into `main` branch?

Maybe we can use these kinds of statements with some flag checks that check if the `DEBUG_SIGNIN` mode is on? If we want to use stuff like this we can create a common service for it.

File: src/services/api.ts [hunk 12]
```diff
@@ -0,0 +1,47 @@
...
+        "username": username, 
+        "email": email, 
+        "password": password 
+      }),
+      headers: {
+        'Content-Type': 'application/json',
+      },
+      credentials: 'include',
+    });
+    console.log(response);
```
Comment (HuseyinSimsek7904) [inline src/services/api.ts:33]: Same here.

**Review by HuseyinSimsek7904 — CHANGES_REQUESTED** [review]
I have several questions there and there but overall good work!

File: src/app/panel/page.tsx (hunk 10 above)
Comment (ErtyumPX) [reply src/app/panel/page.tsx:7]: Dude, fuck off :)

File: src/app/panel/auth/LogIn.tsx (hunk 4 above)
Comment (ErtyumPX) [reply src/app/panel/auth/LogIn.tsx:36]: True :+1:

File: src/services/api.ts (hunk 11 above)
Comment (ErtyumPX) [reply src/services/api.ts:16]: I tend to keep the logs just to be sure everything is working. It gives the idea like

If it's 404, the NestJS server may not be working
If the error code is 500, perhaps the SQL server is not running
If it's 401, unauthorized...

Later on before production we can remove all of them. But if you think they are unnecessary, we can directly remove them now. What do you think? @HuseyinSimsek7904

File: src/app/panel/auth/SignUp.tsx (hunk 7 above)
Comment (ErtyumPX) [reply src/app/panel/auth/SignUp.tsx:42]: There is only 2 forms and both have different inputs, I think that would be an over-generalisation

File: src/app/panel/auth/LogIn.tsx (hunk 5 above)
Comment (ErtyumPX) [reply src/app/panel/auth/LogIn.tsx:39]: I think it's better to directly not let the user use them, @Utkub24 what do you think? We can also give a warning with 'only these letter can be used'

Comment (HuseyinSimsek7904) [reply src/app/panel/auth/LogIn.tsx:39]: Yes, that's what I am saying.

File: src/services/api.ts (hunk 11 above)
Comment (HuseyinSimsek7904) [reply src/services/api.ts:16]: I think it is okay to keep them, however, let's at least add an explanation on what this is.

Maybe something like:
```suggestion
    console.log("Received response from signIn API: ", response);
```

Comment (ErtyumPX) [reply src/services/api.ts:16]: Cool :+1:

File: src/app/panel/auth/LogIn.tsx (hunk 5 above)
Comment (Utkub24) [reply src/app/panel/auth/LogIn.tsx:39]: Yeah, let's not replace them. Instead let the user type it in but just don't allow it to be registered. I felt like my was not working when I tried to type @

File: src/middleware.ts (hunk 1 above)
Comment (ErtyumPX) [reply src/middleware.ts:28]: I tried generalising the headers in a previous projects, it changes in every request and it becomes unnecessary, this also helps you see the headers and other info directly, so I believe it's better not to :+1:

**Comment by ErtyumPX** [comment]
I had a few issues with the regex in javascript, I'll come back to this part soon

**Comment by ErtyumPX** [comment]
Is everything cool with the last commits @HuseyinSimsek7904 ?

**Review by HuseyinSimsek7904 — APPROVED** [review]
Cool, good work! :+1:

**Comment by HuseyinSimsek7904** [comment]
@Utkub24 Please add auto branch deleting i can't figure it out :pray::rofl:
